[platformio]
default_envs = esp32dev

[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
  PubSubClient@^2.8
  ArduinoJson@^6.21
  WiFiClientSecure

[env:pump_esp32]
board_build.partitions = huge_app.csv
build_flags =
  -DDEVICE_TYPE=\"water_pump\"

[env:sensor_esp32]
board_build.partitions = huge_app.csv
build_flags =
  -DDEVICE_TYPE=\"sensor\"
